# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update result

on:
  workflow_dispatch :
  schedule:
    - cron: '0 0 10 * *'

permissions:
  contents: write

jobs:
  fetch-data:

    runs-on: ubuntu-latest

    steps:
    - run: echo "DATETIME=$(TZ=Asia/Taipei date +%Y-%m-%d)" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Crawling...
      run: |
        python main.py
    - name: Push back to repo
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update ${{ env.DATETIME }}
